package tests

import (
	"context"
	"fmt"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/maborak/mabo-tunnel/internal/server"
	"github.com/gorilla/websocket"
)

// The suite runs entirely in-process. Previously it dialed the live
// deployment, which meant the tests could not gate a commit, could not run
// without network, and needed a production credential committed to the repo.
//
// TestMain stands up a Mabo Tunnel server on a loopback port and points every test
// at it. These are vars rather than consts so the harness can fill them in.
var (
	baseURL string // http://127.0.0.1:PORT
	wsURL   string // ws://127.0.0.1:PORT/tunnel/connect
	tsHost  string // 127.0.0.1:PORT

	// testDomain is the base domain the in-process server routes on. Tests
	// reach a tunnel by setting the Host header to <subdomain>.<testDomain>,
	// which needs no DNS.
	testDomain = "mabo-tunnel.test"

	// Tokens exist only in the temporary users file this harness writes.
	proToken  = "test-pro-token-0000000000000000"
	freeToken = "test-free-token-000000000000000"
	fakeToken = "not-a-real-token-00000000000000"

	proUser  = "testpro"
	freeUser = "testfree"
)

// testServer is the running in-process server, for tests that need to reach it.
var testServer *server.Server

func TestMain(m *testing.M) {
	usersFile, cleanup, err := writeTestUsers()
	if err != nil {
		fmt.Fprintf(os.Stderr, "harness: %v\n", err)
		os.Exit(1)
	}
	defer cleanup()

	srv, err := server.New(server.Config{
		Addr:      "127.0.0.1:0", // unused; we mount the handler in httptest
		Domain:    testDomain,
		UsersFile: usersFile,
		LogLevel:  "error", // keep test output readable
		// Keep the auth rate limit tight and short so the limiting test can
		// observe both the block and the recovery in a second, not a minute.
		RateLimitMax:      5,
		RateLimitWindow:   2 * time.Second,
		KeepaliveInterval: 500 * time.Millisecond,
		KeepaliveTimeout:  4 * time.Second,
		// A tunnel whose client never answers should 504 quickly here rather
		// than after the production minute.
		UpstreamHeaderTimeout: 3 * time.Second,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "harness: server.New: %v\n", err)
		os.Exit(1)
	}
	testServer = srv

	ts := httptest.NewServer(srv)
	baseURL = ts.URL
	tsHost = strings.TrimPrefix(ts.URL, "http://")
	wsURL = "ws://" + tsHost + "/tunnel/connect"

	code := m.Run()

	ts.Close()
	srv.Close()
	cleanup()
	os.Exit(code)
}

// writeTestUsers creates a throwaway users file for the suite.
func writeTestUsers() (path string, cleanup func(), err error) {
	dir, err := os.MkdirTemp("", "mabo-tunnel-test-users")
	if err != nil {
		return "", func() {}, err
	}
	path = filepath.Join(dir, "users.txt")
	content := fmt.Sprintf("# generated by the test harness\n%s:%s:pro\n%s:%s:free\n", proToken, proUser, freeToken, freeUser)
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		os.RemoveAll(dir)
		return "", func() {}, err
	}
	return path, func() { os.RemoveAll(dir) }, nil
}

// tunnelHost returns the Host header value that routes to a subdomain.
func tunnelHost(subdomain string) string {
	return subdomain + "." + testDomain
}

// newTestHTTPClient returns a client that sends every request to the test
// server regardless of the hostname in the URL, so tests can use realistic
// tunnel URLs without DNS.
func newTestHTTPClient(timeout time.Duration) *http.Client {
	return &http.Client{
		Timeout: timeout,
		Transport: &http.Transport{
			DialContext: func(ctx context.Context, network, _ string) (net.Conn, error) {
				return net.Dial(network, tsHost)
			},
		},
	}
}

// newTestDialer returns a WebSocket dialer for the in-process server.
func newTestDialer() *websocket.Dialer {
	return &websocket.Dialer{
		HandshakeTimeout: 10 * time.Second,
		NetDial: func(network, _ string) (net.Conn, error) {
			return net.Dial(network, tsHost)
		},
	}
}

// waitFor polls cond until it holds or the deadline passes. Tests use this
// instead of a fixed sleep, so they finish as soon as the condition is met.
func waitFor(t *testing.T, timeout time.Duration, cond func() bool) bool {
	t.Helper()
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		if cond() {
			return true
		}
		time.Sleep(10 * time.Millisecond)
	}
	return cond()
}
