package edge

import (
	"context"
	"fmt"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/maborak/mabo-tunnel/internal/server"
	"github.com/gorilla/websocket"
)

// These are edge-case tests against an in-process server, not probes against a
// deployment. Everything the tests need — the base URL, the domain, the tokens
// — is produced here.
//
// The server's timing is configured down from production values so behavior
// that is defined in terms of a window (rate limiting, keepalive) can be
// observed in seconds instead of waited out in real time.
var (
	baseURL string // http://127.0.0.1:PORT
	wsURL   string // ws://127.0.0.1:PORT/tunnel/connect
	tsHost  string // 127.0.0.1:PORT

	domain = "mabo-tunnel.test"

	proToken  = "test-pro-token-0000000000000000"
	fakeToken = "not-a-real-token-00000000000000"
)

const (
	// rateLimitMax and rateLimitWindow mirror the server config below, so the
	// tests can reason about when limiting starts and when it clears.
	rateLimitMax    = 5
	rateLimitWindow = 2 * time.Second

	// keepaliveInterval is the server's ping cadence here. The keepalive test
	// idles for several multiples of it.
	keepaliveInterval = 500 * time.Millisecond
	keepaliveTimeout  = 4 * time.Second
)

func TestMain(m *testing.M) {
	usersFile, cleanup, err := writeTestUsers()
	if err != nil {
		fmt.Fprintf(os.Stderr, "harness: %v\n", err)
		os.Exit(1)
	}

	srv, err := server.New(server.Config{
		Addr:                  "127.0.0.1:0",
		Domain:                domain,
		UsersFile:             usersFile,
		LogLevel:              "error",
		RateLimitMax:          rateLimitMax,
		RateLimitWindow:       rateLimitWindow,
		KeepaliveInterval:     keepaliveInterval,
		KeepaliveTimeout:      keepaliveTimeout,
		UpstreamHeaderTimeout: 3 * time.Second,
	})
	if err != nil {
		fmt.Fprintf(os.Stderr, "harness: server.New: %v\n", err)
		cleanup()
		os.Exit(1)
	}

	ts := httptest.NewServer(srv)
	baseURL = ts.URL
	tsHost = strings.TrimPrefix(ts.URL, "http://")
	wsURL = "ws://" + tsHost + "/tunnel/connect"

	code := m.Run()

	ts.Close()
	srv.Close()
	cleanup()
	os.Exit(code)
}

func writeTestUsers() (path string, cleanup func(), err error) {
	dir, err := os.MkdirTemp("", "mabo-tunnel-edge-users")
	if err != nil {
		return "", func() {}, err
	}
	path = filepath.Join(dir, "users.txt")
	content := fmt.Sprintf("# generated by the edge test harness\n%s:testpro:pro\n", proToken)
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		os.RemoveAll(dir)
		return "", func() {}, err
	}
	return path, func() { os.RemoveAll(dir) }, nil
}

// newTestHTTPClient dials the in-process server regardless of the hostname in
// the URL, so tunnel hostnames need no DNS.
func newTestHTTPClient(timeout time.Duration) *http.Client {
	return &http.Client{
		Timeout: timeout,
		Transport: &http.Transport{
			DialContext: func(ctx context.Context, network, _ string) (net.Conn, error) {
				return net.Dial(network, tsHost)
			},
		},
	}
}

func newTestDialer() *websocket.Dialer {
	return &websocket.Dialer{
		HandshakeTimeout: 10 * time.Second,
		NetDial: func(network, _ string) (net.Conn, error) {
			return net.Dial(network, tsHost)
		},
	}
}

// clearRateLimit waits just past the limiter's window so a later test starts
// from a clean slate.
func clearRateLimit() {
	time.Sleep(rateLimitWindow + 500*time.Millisecond)
}
