// embed-secrets reads secrets from flags/env/files, encrypts them with
// AES-256-GCM, and generates a Go source file with the encrypted data and the
// XOR-split key. The generated file is compiled into the AIO server binary so
// it needs no config files or env vars on the host.
//
// The encryption is obfuscation, not a secret store: both halves of the key
// live in the same binary, so anyone with the binary can recover the secrets.
// It keeps the token and user database out of loose files and out of a plain
// `strings` dump, nothing more.
package main

import (
	"crypto/rand"
	"flag"
	"fmt"
	"os"
	"strings"

	"github.com/maborak/mabo-tunnel/internal/secrets"
)

func main() {
	domain := flag.String("domain", envOr("MABO_TUNNEL_DOMAIN", "tunnel.example.com"), "Domain")
	aioBind := flag.String("aio-bind", envOr("MABO_TUNNEL_AIO_BIND", "0.0.0.0"), "Bind IP")
	aioEmail := flag.String("aio-email", envOr("MABO_TUNNEL_AIO_EMAIL", ""), "ACME email")
	aioCertPath := flag.String("aio-cert-path", envOr("MABO_TUNNEL_AIO_CERT_PATH", "data/certs"), "Cert path")
	aioCFToken := flag.String("aio-cf-token", envOr("CF_API_TOKEN", ""), "Cloudflare API token")
	usersFile := flag.String("users-file", envOr("MABO_TUNNEL_USERS_FILE", "data/users.txt"), "Path to users.txt")
	output := flag.String("output", "cmd/server/embedded.go", "Output Go source file")
	_ = flag.Bool("hardened", false, "Deprecated: runtime checks were removed; flag is accepted and ignored")
	flag.Parse()

	if *aioCFToken == "" {
		fmt.Fprintln(os.Stderr, "Error: --aio-cf-token or CF_API_TOKEN is required")
		os.Exit(1)
	}
	if *aioEmail == "" {
		fmt.Fprintln(os.Stderr, "Error: --aio-email or MABO_TUNNEL_AIO_EMAIL is required")
		os.Exit(1)
	}

	usersData, err := os.ReadFile(*usersFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading users file: %v\n", err)
		os.Exit(1)
	}

	// Generate random key.
	baseKey := make([]byte, 32)
	if _, err := rand.Read(baseKey); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating key: %v\n", err)
		os.Exit(1)
	}

	encCFToken, err := secrets.Encrypt(baseKey, []byte(*aioCFToken))
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error encrypting CF token: %v\n", err)
		os.Exit(1)
	}
	encUsersData, err := secrets.Encrypt(baseKey, usersData)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error encrypting users data: %v\n", err)
		os.Exit(1)
	}

	keyPart1, keyPart2, err := secrets.SplitKey(baseKey)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error splitting key: %v\n", err)
		os.Exit(1)
	}

	var b strings.Builder
	b.WriteString("// Code generated by embed-secrets. DO NOT EDIT.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/maborak/mabo-tunnel/internal/secrets\"\n")
	b.WriteString(")\n\n")

	b.WriteString("func init() {\n")
	b.WriteString("\t// Config (non-secret).\n")
	b.WriteString(fmt.Sprintf("\tembeddedDomain = %q\n", *domain))
	b.WriteString(fmt.Sprintf("\tembeddedAIOBind = %q\n", *aioBind))
	b.WriteString(fmt.Sprintf("\tembeddedAIOEmail = %q\n", *aioEmail))
	b.WriteString(fmt.Sprintf("\tembeddedAIOCertPath = %q\n", *aioCertPath))
	b.WriteString("\tembeddedAIO = true\n\n")

	b.WriteString("\t// Reconstruct the key from XOR-split parts.\n")
	b.WriteString(fmt.Sprintf("\tkey := secrets.JoinKey(%s, %s)\n\n", goBytes(keyPart1), goBytes(keyPart2)))

	b.WriteString("\t// Decrypt secrets.\n")
	b.WriteString(fmt.Sprintf("\tif v, err := secrets.Decrypt(key, %s); err == nil { embeddedCFToken = string(v) }\n", goBytes(encCFToken)))
	b.WriteString(fmt.Sprintf("\tif v, err := secrets.Decrypt(key, %s); err == nil { embeddedUsersData = string(v) }\n", goBytes(encUsersData)))
	b.WriteString("}\n")

	if err := os.WriteFile(*output, []byte(b.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "Error writing output: %v\n", err)
		os.Exit(1)
	}

	fmt.Fprintf(os.Stderr, "Generated %s (encrypted, %d users bytes)\n", *output, len(usersData))
}

func goBytes(b []byte) string {
	var parts []string
	for _, v := range b {
		parts = append(parts, fmt.Sprintf("0x%02x", v))
	}
	return "[]byte{" + strings.Join(parts, ", ") + "}"
}

func envOr(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
